#ifndef _CRC32C_STATUS
#define _CRC32C_STATUS
typedef enum { ST_SUCCESS, ST_SOCKET_CREATE_FAILED, ST_SOCKET_BIND_FAILED, ST_SOCKET_ACCEPT_FAILED, ST_SOCKET_SEND_FAILED, ST_SOCKET_READ_FAILED } CRC32C_Status;
#endif // _CRC32C_STATUS
